### PR TITLE
Support React 19

### PR DESCRIPTION
**Pull request by pechersky**
By loosening `peerDependencies`

## Actions

- [x] Added description of changes to the `[Unreleased]` section of `CHANGELOG.md`
- [x] Updated headers of modified files
- [x] Added my name to `package.json`'s `contributors`
- [x] (Optional but encouraged) Improved documentation in `docs`

### CODE REVIEW

**Comment by pechersky** [comment]
Could also do it by adding more `^19.0.0 ||` style to peerDependencies. Do we need to have react at all in peer deps?

**Comment by dsehnal** [comment]
This change looks fine. We don't "need it", but it's still quite integral,

**Comment by dsclassen** [comment]
Is it safe to assume that this problem will go away in a couple days when this PR gets released with the next version bump?

```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: molstar@4.9.1
npm error Found: react@19.0.0
npm error node_modules/react
npm error   react@"19.0.0" from the root project
npm error   peer react@">=16.8.0" from @emotion/react@11.14.0
npm error   node_modules/@emotion/react
npm error     @emotion/react@"^11.14.0" from the root project
npm error     peer @emotion/react@"^11.0.0-rc.0" from @emotion/styled@11.14.0
npm error     node_modules/@emotion/styled
npm error       @emotion/styled@"^11.14.0" from the root project
npm error       5 more (@mui/x-data-grid, @mui/material, @mui/lab, @mui/system, @mui/styled-engine)
npm error     5 more (@mui/x-data-grid, @mui/material, @mui/lab, @mui/system, @mui/styled-engine)
npm error   26 more (@emotion/styled, ...)
npm error
npm error Could not resolve dependency:
npm error peer react@"^18.1.0 || ^17.0.2 || ^16.14.0" from molstar@4.9.1
npm error node_modules/molstar
npm error   molstar@"^4.9.1" from the root project
npm error
npm error Conflicting peer dependency: react@18.3.1
npm error node_modules/react
npm error   peer react@"^18.1.0 || ^17.0.2 || ^16.14.0" from molstar@4.9.1
npm error   node_modules/molstar
npm error     molstar@"^4.9.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
```

**Comment by arose** [comment]
yes, will release on the weekend

**Comment by pechersky** [comment]
In the meantime you can do `npm install --legacy-peer-deps` to ignore peerDependency mismatches

**Pull request merged**
