### PR TITLE
Separed postprocessing passes

### PR DESCRIPTION
**Pull request by giagitom**
# Description
Split postprocessing passes in different files to simplify postprocessing file structure.

## Actions

- [x] Added description of changes to the `[Unreleased]` section of `CHANGELOG.md`
- [x] Updated headers of modified files
- [ ] Added my name to `package.json`'s `contributors`
- [ ] (Optional but encouraged) Improved documentation in `docs`

### CODE REVIEW

**Review by arose — CHANGES_REQUESTED** [review]
Thanks for doing this!

Played around with it to see if it all still works and found changing the occlusion resolution parameter around a few times (lower then higher) does work correctly and will eventually throw an error.

**Comment by giagitom** [comment]
>Played around with it to see if it all still works and found changing the occlusion resolution parameter around a few times (lower then higher) does work correctly and will eventually throw an error.

@arose do you have a test state to reproduce? I tried extensively modifying every occlusion parameter but haven't found errors so far.

**Comment by arose** [comment]
Cant be shown with a state. I get it by moving the resolutionScale param around

image

**Comment by giagitom** [comment]
So I wasn't seeing anything because I was using viewport settings. I'm not sure why but it seems that using viewport settings it is also triggered the resize of passes. Instead using the other settings resize is not triggered. Maybe this is causing the error? 

Any Idea on what is going on?

image

**Comment by giagitom** [comment]
Fixed the issue causing errors with last commit

**Comment by giagitom** [comment]
@arose I resolved conflicts due to #1211

It should be ready now

**Comment by giagitom** [comment]
Is it correct to use ```nearest``` here?

https://github.com/molstar/molstar/blob/18b1492d54ba3e2beee47bda6ac262ef8b8881c7/src/mol-canvas3d/passes/postprocessing.ts#L142-L144

**Comment by arose** [comment]
should be 'linear' if available, but actually that schema info it is not used.

**Pull request merged**
