### PR TITLE
Resolve marking in main render loop

### LINKED ISSUE #382: Performance Impact of Temporal Multi-Sample
The sequence panel is quite laggy after the default multi-sample mode was changed to temporal. This gets intensified if there are additional subscribers to these events.

https://recordit.co/ZA0LVYkZBc

Is it possible to address this or should one just disable multi-sampling when running into this issue? Thanks!

### PR DESCRIPTION
**Pull request by dsehnal**
- Apply making in the main render loop instead of calling the draw function eagerly each time marking changes.
- Use ``throttleTime`` instead of ``debounceTime`` in the sequence viewer (felt better overall).

Should fix #382.

### CODE REVIEW

**Review by JonStargaryen — APPROVED** [review]
Many thanks, way more responsive now :)

LGTM, only spotted a typo (rernder) in the changelog.

**Review by arose — COMMENTED** [review]
I like it, quite better than before. There is a regression. When just moving the mouse (no drag, no camera movement) it should do the multi-sampling in one pass (the forceOn flag), otherwise you get this annoying flicker.

**Comment by dsehnal** [comment]
> I like it, quite better than before. There is a regression. When just moving the mouse (no drag, no camera movement) it should do the multi-sampling in one pass (the forceOn flag), otherwise you get this annoying flicker.

@arose did [486d12b](https://github.com/molstar/molstar/pull/383/commits/486d12b6ac48bafe741fc8dad464dd1acad9146a) fix this?

**Comment by arose** [comment]
Yeah, that looks good! Thanks

**Pull request merged**
