### PR TITLE
keep asset url to detect compression

### PR DESCRIPTION
**Pull request by JonStargaryen**
# Description
Tiny quality-of-life improvement that extends the handling of zip/gzip assets to URLs.
https://files.rcsb.org/download/4HHB.cif.gz
https://files.rcsb.org/download/4HHB.pdb.gz
https://models.rcsb.org/4HHB.bcif.gz

## Actions

- [x] Added description of changes to the `[Unreleased]` section of `CHANGELOG.md`
- [ ] Updated headers of modified files
- [ ] Added my name to `package.json`'s `contributors`

### CODE REVIEW

**Review by dsehnal — COMMENTED** [review]
It looks fine, hopefully won't bite us... what if the URL will have the .gz there, but will have content-encoding set as well?

**Comment by dsehnal** [comment]
Maybe we can check the response headers and only add the "filename" if it doesn't have the gzip content encoding?

**Comment by JonStargaryen** [comment]
> what if the URL will have the .gz there, but will have content-encoding set as well?

That's actually the case for https://models.rcsb.org/4HHB.bcif.gz (should fix that though...) and it works.

> Maybe we can check the response headers and only add the "filename" if it doesn't have the gzip content encoding?

Hmm, I tried to check headers inside of ajaxGetInternal() but content-encoding isn't set at that point. Chrome at least seems to handle/hide all of that (content-encoding = gzip appears in the network tab).

Another, more resilient, solution would be to check the first few bytes of the file for zip/gzip magic numbers and decompress as needed. That would work independent of the URL (or file extension) but has drawbacks as well.

That said, this is also fine to keep as is. Just saw this during testing and thought it would be nice/convenient to have.

**Comment by dsehnal** [comment]
> That's actually the case for https://models.rcsb.org/4HHB.bcif.gz (should fix that though...) and it works.

Are you double gzipping your responses?

**Comment by JonStargaryen** [comment]
Apparently for that endpoint :(

**Comment by dsehnal** [comment]
Ok, this should not break anything... hopefully :)

**Comment by JonStargaryen** [comment]
@dsehnal This indeed breaks anything related to validation reports (https://files.rcsb.org/pub/pdb/validation_reports/hh/4hhb/4hhb_validation.xml.gz). The browser handles the encoding and now Mol* trips up when trying to "decompress" the XML. 

Should we just revert this PR?

**Comment by dsehnal** [comment]
Yea. And need new release then. Can you make a pr which undoes this?

**Comment by JonStargaryen** [comment]
Sure thing, will do later today.

**Pull request merged**
