### PR TITLE
Add labels for Confal pyramids

### PR DESCRIPTION
**Pull request by MadCatX**
My original intention was to just add labels to Confal pyramids. In retrospect I realized that some of the naming used in the code was quite misleading so I tried to improve upon that as well.

### CODE REVIEW

**Comment by arose** [comment]
Looks good to me and reads cleaner than before.

Unrelated to the changes here but could you add a small example mmcif file to `./examples/` to simplify cursory testing of the confal pyramids?

**Comment by arose** [comment]
Please add a short note to the Changelog even if you just did internal refactoring.

**Comment by MadCatX** [comment]
Thanks! I've added an example file and updated the changelog accordingly. Hopefully I'll have some code less mundane that this to propose in the upcoming weeks...

**Comment by arose** [comment]
Thank you for the changes.

**Pull request merged**
