### PR TITLE
Stop showing `computed` bonds if `chem_comp_bond` is defined

### PR DESCRIPTION
**Pull request by JonStargaryen**
# Description
Follow-up to #641, implementing Alex' proposal.

Works for standard ball-and-stick but doesn't play nicely with focus, which includes `computed` interactions by default (and adding it to `excludeTypes` removes other bonds, but removing it from `includeTypes` gives the visuals I'd like, at least for [1t2c](https://molstar.org/viewer/?load-pdb=1t2c)).

Do you have an idea for that? All archive mmCIF will have `chem_comp_bond` by the end of the year, currently available for ~160k.

## Actions

- [x] Added description of changes to the `[Unreleased]` section of `CHANGELOG.md`
- [x] Updated headers of modified files
- [ ] Added my name to `package.json`'s `contributors`
- [ ] (Optional but encouraged) Improved documentation in `docs`

### CODE REVIEW

**Review by arose — CHANGES_REQUESTED** [review]
Did you try adding logic to StructureFocusRepresentationBehavior.focus?

The lines representation should have the same check as you did for the ball-and-stick representation.

**Comment by JonStargaryen** [comment]
Thanks for the pointers. How about these changes?
The focus surroundings now toggle `includeTypes` depending on the structure.

**Review by dsehnal — COMMENTED** [review]
I am not quite sure this will have the desired effect, since chem comp bond only contains bonds within a single residue and you seem to apply this in a much wider context for all bonds. Or am I missing something?

**Comment by JonStargaryen** [comment]
Maybe there's also something I don't get about `includeTypes` and `excludeTypes`. I assumed that removing `computed` from `includeTypes` would have the same effect as adding it to `excludeTypes`, but the results differ.

Adding it to `excludeTypes` will corrupt bonds between components (using the default 1tqn as example):
exclude


Removing it to `includeTypes` gives the desired visuals:
include


Original:
orig



It's also fine to keep things as is. A team member asked about these visuals but lets ignore if this does more harm than good.

**Comment by arose** [comment]
> It's also fine to keep things as is. A team member asked about these visuals but lets ignore if this does more harm than good.

Yes, let's can it for now.

I think to make it work for mmcif files we at least need a way to derive polymer bonds from the sequence and mark them as not computed.

**Pull request closed without merging**
