### PR TITLE
enable immediateUpdate for iso level

### PR DESCRIPTION
**Pull request by arose**

### CODE REVIEW

**Comment by arose** [comment]
@dsehnal any objections? bad idea?

**Comment by dsehnal** [comment]
@arose Hmm, now about at least introducing a ~0.5s delay for the change?

Otherwise I can see this leading to a very unpleasant UX for some cases.

**Comment by arose** [comment]
How would you do that? We don't do for modelIndex update.

**Comment by dsehnal** [comment]
Change ``{ immediateUpdate?: boolean | { debounceTimeMs: number } }`` and then pass this down to the control. The update itself would then be wrapped in a ``BehaviorSubject`` with ``.pipe(debounceTime(...)).subscribe()`` or just manual ``setTimeout``.

**Comment by dsehnal** [comment]
On a second thought, I think we can just do this and implement the debounce later if it causes any problems.

**Comment by arose** [comment]
> On a second thought, I think we can just do this and implement the debounce later if it causes any problems.

:)

**Pull request merged**
