### PR TITLE
Enable odd dash count (1,3,5)

### PR DESCRIPTION
**Pull request by giagitom**
# Description

Allows for odd aromatic dash count (1,3,5)

## Actions

- [ ] Added description of changes to the `[Unreleased]` section of `CHANGELOG.md`
- [ ] Updated headers of modified files
- [ ] Added my name to `package.json`'s `contributors`

### CODE REVIEW

**Comment by arose** [comment]
Haven't looked in detail but in general this should also be supported for lines and mesh-based cylinders

**Comment by giagitom** [comment]
Yes, I'll do that, but prefer to wait for your feedback before, in case there is something to be changed

**Comment by arose** [comment]
If you want to be fancy you can hide the caps of the dashes that meet for odd counts (unless they are stubs).

image

Other wise looks good, apart from that it should also be supported for lines and mesh-based cylinders as already mentioned.

**Review by arose — CHANGES_REQUESTED** [review]
If you want to be fancy you can hide the caps of the dashes that meet for odd counts (unless they are stubs).

image

Other wise looks good, apart from that it should also be supported for lines and mesh-based cylinders as already mentioned.

Would be nice to allow odd dash counts for non-aromatic dashes, too, for example, used in interactions.

**Comment by giagitom** [comment]
Should have done everything with last commit. Also supporting non aromatic odd dash count.

image

image

**Review by arose — CHANGES_REQUESTED** [review]
nice changes, thank you!

dashes lines are not looking quite right

image

please add a changelog entry

**Comment by giagitom** [comment]
Should be fixed now for meshes, lines and impostors.

image

**Comment by arose** [comment]
Thanks for the changes. The aromatic dashes look different for impostor and non-imposter variant. They should look like the non-imposter variant where the dashes do not overlap.

image

image

**Comment by giagitom** [comment]
It should be equal now.

**Review by arose — APPROVED** [review]
thanks @giagitom, quite nice, looks all good to me now

**Pull request merged**
