### PR TITLE
Adjust VolumeRepresentation#setState

### PR DESCRIPTION
**Pull request by JonStargaryen**
# Description
This brings back the behavior where one can hide volume certain channels and they won't reappear later on, e.g. when focusing on a residue.
Adjusts other properties as well. Let me know if this has any implications.

## Actions

- [x] Added description of changes to the `[Unreleased]` section of `CHANGELOG.md`
- [ ] Updated headers of modified files
- [ ] Added my name to `package.json`'s `contributors`

### CODE REVIEW

**Review by arose — COMMENTED** [review]
Looks good to me. Could you also change `src\mol-repr\structure\units-representation.ts`?

**Comment by JonStargaryen** [comment]
Done in https://github.com/molstar/molstar/pull/835/commits/627636576674002fc4ff0914cc5906f9b836a858. 

Should the 2nd expression in https://github.com/molstar/molstar/blob/627636576674002fc4ff0914cc5906f9b836a858/src/mol-repr/structure/units-representation.ts#L280 check against the version of `_state` and not `state`?

**Comment by arose** [comment]
> Done in [6276365](https://github.com/molstar/molstar/commit/627636576674002fc4ff0914cc5906f9b836a858).
> 

thanks

> Should the 2nd expression in
> 
> https://github.com/molstar/molstar/blob/627636576674002fc4ff0914cc5906f9b836a858/src/mol-repr/structure/units-representation.ts#L280
> check against the version of `_state` and not `state`?

Yes please

**Comment by JonStargaryen** [comment]
OK, updated as well.

**Pull request merged**
