### PR TITLE
Make Trackball spin in radians per second

### PR DESCRIPTION
**Pull request by bergwerf**
# Description

The trackball spin animation is carried out via the same mechanism as pointer drag rotation, which takes the canvas aspect ratio into account via `getRotateFactor`. It might make more sense to set a spin animation to a constant speed in radians per second. The least invasive way to do this is to compensate for `getRotateFactor` when the spin animation is applied.

## Actions

- [x] Added description of changes to the `[Unreleased]` section of `CHANGELOG.md`
- [x] Updated headers of modified files
- [x] Added my name to `package.json`'s `contributors`
- [ ] (Optional but encouraged) Improved documentation in `docs`

### CODE REVIEW

**Comment by dsehnal** [comment]
> The trackball spin animation is carried out via the same mechanism as pointer drag rotation, which takes the canvas aspect ratio into account via getRotateFactor. It might make more sense to set a spin animation to a constant speed in radians per second. The least invasive way to do this is to compensate for getRotateFactor when the spin animation is applied.

I am ok with changing this to `rad/s` instead of scaling this to "60 fps" as it is now, but I don't see reasoning behind the `getRotateFactor`, since that is there because it is tied to user input, but the "spin" isn't. 

@arose what do you think?

**Comment by bergwerf** [comment]
In the current implementation the spin animation gets multiplied by a perhaps unintended `getRotateFactor`, so if the viewport is very elongated the spin animation is several times slower. This change counteracts that by dividing that factor out. When the spin animation is applied, it adds a delta-x to `_rotCurr`. When the camera is updated, the difference between `_rotCurr` and `_rotPrev` are translated into a rotation. This mechanism was presumably first developed for the user dragging a pointer. Instead of making the code more complex with a separate mechanism for absolute rotation (e.g. in terms of an axis and an angle, instead of two pointer positions), this change just divides out the `getRotateFactor`.

To me changing into radians per second is not essential, but it would be nice if the rotation speed is constant no matter the aspect ratio of the viewport.

**Comment by bergwerf** [comment]
This is the relevant line: https://github.com/molstar/molstar/blob/88e7c4c640059d29aa88217922bfc57c6b7dcd79/src/mol-canvas3d/controls/trackball.ts#L212

**Comment by dsehnal** [comment]
Right, I missed that. Makes sense.

**Comment by dsehnal** [comment]
@bergwerf Can you also add the changelog note, etc?

**Comment by bergwerf** [comment]
@dsehnal Yes done.

**Review by dsehnal — APPROVED** [review]

**Pull request merged**
