### PR TITLE
Add include transparent parameter for outlines

### PR DESCRIPTION
**Pull request by arussell123**
# Description
Add a parameter to the outline settings to choose whether to show the outlines for transparent components.

## Actions

- [x] Added description of changes to the `[Unreleased]` section of `CHANGELOG.md`
- [ ] Updated headers of modified files
- [ ] Added my name to `package.json`'s `contributors`

### CODE REVIEW

**Comment by arose** [comment]
Thank you for doing this! I was thinking more of a flag to toggle outlines for anything with opacity < 1. We may want to use the transparent depth buffer for other things than outlines.

I would add a `includeTransparent` param to `PostprocessingParams.outline` and then add a define to `getDepthTransparent` in `outlines.frag` and `postprocessing.frag` to return 1.0 when switched off

```
float getDepthTransparent(const in vec2 coords) {
    #ifdef dTransparentOutline
        return unpackRGBAToDepth(texture2D(tDepthTransparent, coords));
    #else
        return 1.0;
    #endif
}
```

You should also rename `PostprocessingPass.isOutlineEnabled` to `PostprocessingPass.isTransparentOutlineEnabled` and check if transparent outlines are on to avoid doing a depth pass.

**Comment by arose** [comment]
Thank you for the changes @arussell123. Could you please also replace `PostprocessingPass.isOutlineEnabled` with

```
static isTransparentOutlineEnabled(props: PostprocessingProps) {
    return props.outline.name === 'on' && props.outline.params.includeTransparent;
}
```

this should avoid doing the extra depth pass for transparent outlines in `mol-canvas3d/passes/draw.ts`

**Comment by arussell123** [comment]
Ah good point, I'll change it now!

**Comment by arose** [comment]
splendid, thank you @arussell123

**Pull request merged**
