### PR TITLE
Parse CCD Files

### PR DESCRIPTION
**Pull request by JonStargaryen**
# Description
Allows loading of CCD `.cif` files (https://github.com/molstar/molstar/issues/625).
Some test URLs:
https://files.rcsb.org/ligands/view/HEM.cif
https://files.rcsb.org/ligands/view/TRP.cif
https://files.rcsb.org/ligands/view/CA.cif

## Actions

- [x] Added description of changes to the `[Unreleased]` section of `CHANGELOG.md`
- [x] Updated headers of modified files
- [x] Added my name to `package.json`'s `contributors`

### CODE REVIEW

**Comment by JonStargaryen** [comment]
Two questions:
- Should `ideal` coordinates be center on the `model` ones? Otherwise switching between models is quite confusing.
- How does `maxDistance` of `IndexPairBonds` work? Shouldn't it take the bonds at face value when the default value of `-1` is used? It suppresses a long bond in the ideal HEM coordinates and I can only get it to show up if I set `maxDistance` to some large value.

HEM-ideal

**Comment by arose** [comment]
> Should ideal coordinates be centered on the model ones? Otherwise switching between models is quite confusing.

Hmm, how about adding a HierarchyPreset that creates two Structures which you can translate or align any way you like?

> How does maxDistance of IndexPairBonds work? Shouldn't it take the bonds at face value when the default value of -1 is used? It suppresses a long bond in the ideal HEM coordinates and I can only get it to show up if I set maxDistance to some large value.

You would need to actually provide a distance column in the IndexPairBonds data. However, setting maxDistance to 4 or so, seems fine here. But before that we should check if the distance in src\mol-model\structure\structure\unit\bonds\common.ts needs some tweaking.

**Comment by arose** [comment]
Regarding the bonds, can you add them using the `ComponentBond.Provider`

https://github.com/molstar/molstar/blob/aeab0f235c6af58a8693b6b5b34f1788a99dfa4c/src/mol-model-formats/structure/mmcif.ts#L50-L59

that way they should all get added regardless of distance and metal bonds get also flagged

**Comment by arose** [comment]
@JonStargaryen much better, thanks. Can you add a changelog entry, please. Are considering to look into adding a HierarchyPreset or should I merge it?

**Comment by JonStargaryen** [comment]
> Are considering to look into adding a HierarchyPreset or should I merge it?

I'll try to have a look next week.

**Comment by JonStargaryen** [comment]
Got held back a bit. Did you have something like [cc9bdd4](https://github.com/molstar/molstar/pull/731/commits/cc9bdd4f14507c47bceca6fa06d28b1ed0cc3b95) in mind? Just checking that I'm heading in the right direction.

**Comment by arose** [comment]
> Got held back a bit. Did you have something like [cc9bdd4](https://github.com/molstar/molstar/pull/731/commits/cc9bdd4f14507c47bceca6fa06d28b1ed0cc3b95) in mind? Just checking that I'm heading in the right direction.

Yes, that looks nice. How about adding a representation-preset with separate components for the ideal and model structure?

**Comment by JonStargaryen** [comment]
Alright, made some progress and added a representation-preset that creates 2 components and shows `ideal` coordinates by default. Fixed representation and alignment routine for cases where `ideal` and `model` coordinates differ and some atoms aren't present.

I've added `CCDCoordinateTypeProp` but that's probably overkill, though I didn't find a better way differentiate between `ideal` or `model` coords at model level.

Finally, here's a list of test/edge cases that might prove helpful:

Ligand | Status | Details
-- | -- | --
https://files.rcsb.org/ligands/view/FE.cif |OK| +3 oxidation state
https://files.rcsb.org/ligands/view/FE2.cif |OK| +2 oxidation state
https://files.rcsb.org/ligands/view/RUC.cif |OK| transition metal
https://files.rcsb.org/ligands/view/SF4.cif | doesn't align nicely | Fe-S cluster
https://files.rcsb.org/ligands/view/TBR.cif |OK| coords identical
https://files.rcsb.org/ligands/view/OER.cif |OK| coords identical
https://files.rcsb.org/ligands/view/FEA.cif |OK| charges (though not handled)
https://files.rcsb.org/ligands/view/PR2.cif |OK| orientation differs
https://files.rcsb.org/ligands/view/03R.cif |doesn't align nicely| some atoms missing
https://files.rcsb.org/ligands/view/02U.cif |OK| many atoms missing
https://files.rcsb.org/ligands/view/HC0.cif |unrelated data issues – O and H atoms clashing| no ideal coords
https://files.rcsb.org/ligands/view/Q6O.cif |OK| no model coords
https://files.rcsb.org/ligands/view/H0C.cif |OK| big ligand
https://files.rcsb.org/ligands/view/HEM.cif |OK| metal coordination
https://files.rcsb.org/ligands/view/UNK.cif | OK, but some model H are placed far away | CCD weirdo
https://files.rcsb.org/ligands/view/UNL.cif | OK, fails to load as expected | CCD weirdo, no coordinates whatsoever
https://files.rcsb.org/ligands/view/UNX.cif |OK| CCD weirdo, no ideal coords
https://files.rcsb.org/ligands/view/2NC.cif |OK|dual representation as PRD and CC
https://files.rcsb.org/birds/view/PRDCC_000001.cif |OK| PRDCC

**Review by arose — CHANGES_REQUESTED** [review]
Great addition, thank you @JonStargaryen.

> Alright, made some progress and added a representation-preset that creates 2 components and shows ideal coordinates by default. Fixed representation and alignment routine for cases where ideal and model coordinates differ and some atoms aren't present.

I suggest to move the presets to extensions/wwpdb/ccd/ as they are somewhat specialized. But keep the `CCDFormat` in the core.

> I've added CCDCoordinateTypeProp but that's probably overkill, though I didn't find a better way differentiate between ideal or model coords at model level.

I agree, that is quite custom for the core library. How about you analyze `model.sourceData` and the `index` from `Model.TrajectoryInfo` to infer which type a model is? That way you can do in the presets in the extension and don't have have it in the core lib.

> Finally, here's a list of test/edge cases that might prove helpful:

Nice! Please add them to extensions/wwpdb/ccd/README.md

**Comment by JonStargaryen** [comment]
Thanks for all the feedback along the way.

> I suggest to move the presets to extensions/wwpdb/ccd/ as they are somewhat specialized. But keep the `CCDFormat` in the core.

Factored out the representations with [38c550b](https://github.com/molstar/molstar/pull/731/commits/38c550b2459d689e57ae2235381b78d24d85caa3).

> I agree, that is quite custom for the core library. How about you analyze `model.sourceData` and the `index` from `Model.TrajectoryInfo` to infer which type a model is? That way you can do in the presets in the extension and don't have have it in the core lib.

Sounds good, done with [95a7a2c](https://github.com/molstar/molstar/pull/731/commits/95a7a2cef99edfc2cd1f278edec763e273a64404).
I didn't add another check based on `sourceData` as that's part of `isApplicable` but let me know if there's a scenario where that's not good enough.

Big-picture-wise, we want to replace NGL on the [Ligand Summary Page](https://www.rcsb.org/ligand/HEM) while retaining the functionality of toggling labels with atom names and/or hydrogens. Might need a 2nd PR to fully support labels.
`LabelRepresentation` is pretty close what I need but there doesn't seem to be a way to keep the labels "in sync" with the state of `ignoreHydrogens` of the ball-and-stick representation (i.e., hide hydrogen labels by default but have them appear on demand). Haven't looked too deeply into this yet. Maybe it's OK to create 2 sets of label representations, one with hydrogens and one without, and adjust their visibility from outside of Mol*.

**Comment by arose** [comment]
> LabelRepresentation is pretty close what I need but there doesn't seem to be a way to keep the labels "in sync" with the state of ignoreHydrogens of the ball-and-stick representation (i.e., hide hydrogen labels by default but have them appear on demand). 

Quick comment on this part. Please do another PR that adds the parameters

```ts
ignoreHydrogens: PD.Boolean(false),
ignoreHydrogensVariant: PD.Select('all', PD.arrayToOptions(['all', 'non-polar'] as const)),
```

to the `LabelTextVisual` similar to what is done in the `ElementSphereImpostorVisual` and others. Doing that should be enough to solve your issue.

**Comment by JonStargaryen** [comment]
Yes, that should do it, will look into it.

**Comment by arose** [comment]
@JonStargaryen I tweaked the coordinate type handling in [f0e725f](https://github.com/molstar/molstar/pull/731/commits/f0e725f65c107a55b0dbd6c424276669f42c4a00). Mainly brought back the model prop but within CCDFormat. Does it look OK to you?

**Comment by JonStargaryen** [comment]
Thanks, looks good to me. Won't hurt to be explicit about the coordinate type.

**Pull request merged**
