### PR TITLE
wrap screenshot & image generation in a Task

### PR DESCRIPTION
**Pull request by arose**
Wrap screenshot & image generation in a `Task`. This will allow observing multi-step image generation in the future.

### CODE REVIEW

**Comment by arose** [comment]
@midlik @JonStargaryen please check if that breaks anything in your image generation apps, thanks.

**Comment by arose** [comment]
ping @midlik @JonStargaryen

**Comment by midlik** [comment]
Hi @arose , sorry for the delay.
I checked `src/examples/image-renderer/index.ts` and `src/cli/mvs/mvs-render.ts` and both work fine.
I also adjusted PDBImages (https://github.com/PDBeurope/pdb-images) so that this change doesn't break it once it's released.

**Comment by JonStargaryen** [comment]
Thanks for the heads-up. Looks straightforward, we'll update molrender after these changes have been released.

**Comment by arose** [comment]
thanks for checking

**Pull request merged**
