### PR TITLE
Generalize rcsb/assembly-symmetry/ extension

### LINKED ISSUE #951: refactor assembly-symmetry extension
follow-up on #950, for v4 due to breaking changes

to make it a bit more generic and reduce maintenance for the molstar project I propose the following
- rename to `AssemblySymmetry` (from `RCSBAssemblySymmetry`) and more to its own extension folder
- remove the graphql schema generation to reduce maintenance burden (only used here)
- review schema and make desired changes

### PR DESCRIPTION
**Pull request by arose**
Generalize rcsb/assembly-symmetry/ extension

- Move to assembly-symmetry/
- Remove RCSB specific dependencies and prefixes

closes #951

### CODE REVIEW

**Comment by arose** [comment]
@midlik @JonStargaryen please have look

**Review by JonStargaryen — APPROVED** [review]
Thanks, LGTM.

**Comment by arose** [comment]
@midlik does this look OK to you?

**Comment by midlik** [comment]
Sorry I didn't respond more promptly, but now I went through it and LGTM

**Pull request merged**
