### PR TITLE
cleaner default representation style

### PR DESCRIPTION
**Pull request by arose**
I am proposing some tweaks to the cartoon and focus representation defaults

- Cartoon: use ``nucleotide-ring`` instead of ``nucleotide-block``
- Focus: use ``xrayShaded`` instead of opacity; adjust target size; don't show non-covalent interactions twice

New
image

Old
image

### CODE REVIEW

**Comment by arose** [comment]
ping @dsehnal @JonStargaryen @mandarsd any objections?

**Comment by dsehnal** [comment]
Looks much better!

**Comment by JonStargaryen** [comment]
Yeah, nice change!

**Comment by dhrblav** [comment]
Nice changes indeed, however I still find the focus highlight hard to see and I suggest a brighter representation.

**Comment by arose** [comment]
> Nice changes indeed, however I still find the focus highlight hard to see and I suggest a brighter representation.

Thanks for the suggestions, that's is a good idea (used that myself before...). Unfortunately it is currently not possible to make all color themes brighter , and the focus representation needs to work for all themes, at least in the generic viewer.

**Pull request merged**
