### PR TITLE
Add round caps on tubular alpha helices

### PR DESCRIPTION
**Pull request by giagitom**
# Description
### This PR adds round caps option on tubular helices

image

### Known issues
 - Normals at the extremities should be smoothed in some way. 
image

- Also not sure why, if caps are near gaps something goes wrong on the cap shape
image
 

## Actions

- [x] Added description of changes to the `[Unreleased]` section of `CHANGELOG.md`
- [x] Updated headers of modified files
- [ ] Added my name to `package.json`'s `contributors`
- [ ] (Optional but encouraged) Improved documentation in `docs`

### CODE REVIEW

**Review by arose — CHANGES_REQUESTED** [review]
Normals definitely look wrong. I like this options but the two issues you note should be fixed before merging.

**Comment by giagitom** [comment]
@arose in last commit i tried to smooth normals. Now vertices are smoothed but colors are wrong. 
Could you check on the approach I am using? I'm not sure this is the correct way of doing this. 
 
image

**Comment by giagitom** [comment]
> Also not sure why, if caps are near gaps something goes wrong on the cap shape

Should be fixed now with [d2192d6](https://github.com/molstar/molstar/pull/1120/commits/d2192d609aa36e4c1c27660787b6937d63d2bdd8) (tested with PDB ID 2XUT)
image

**Comment by giagitom** [comment]
@arose everything should be now fixed.

**Review by arose — APPROVED** [review]
thanks, lgtm

**Pull request merged**
